//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsportrsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id_book { get; set; }
        public Nullable<int> id_computer { get; set; }
        public Nullable<int> id_user { get; set; }
        public System.DateTime date_book { get; set; }
        public System.TimeSpan time_book { get; set; }
        public int duration { get; set; }
        public Nullable<bool> service_food { get; set; }
        public Nullable<bool> service_drink { get; set; }
        public decimal total_price { get; set; }
        public Nullable<int> id_tournament { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual Users Users { get; set; }
    }
}
